"""add location

Revision ID: 96724a442bc8
Revises: 4d4c0a098a88
Create Date: 2025-03-21 21:00:05.227481

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96724a442bc8"
down_revision: Union[str, None] = "4d4c0a098a88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "building",
            sa.Enum("BAYZAK", "MAIN_BUILD", "OTHER", name="buildingsenum"),
            nullable=False,
        ),
        sa.Column("room", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location")
    # ### end Alembic commands ###
